### ISSUE TITLE
Error 404 when trying to download pretrained model files

### ISSUE THREAD

**Issue by schuhschuh** [jamt9000/DVE#3]
http://www.robots.ox.ac.uk/~vgg/research/DVE/data/models/celeba-smallnet-3d-dve/2019-08-08_17-54-21/model_best.pth

"The requested URL /~vgg/research/DVE/data/models/celeba-smallnet-3d-dve/2019-08-08_17-54-21/model_best.pth was not found on this server."

**Comment by albanie** [comment]
Sorry about this, some things have moved around on the server.  Will push a fix asap.

**Comment by albanie** [comment]
Have fixed the paths, but please feel free to re-open if you hit other issues. Thanks!

**Comment by schuhschuh** [comment]
These work, thanks!
