### ISSUE TITLE
Missing test.py?

### ISSUE THREAD

**Issue by schuhschuh** [jamt9000/DVE#5]
In section https://github.com/jamt9000/DVE#regressing-landmarks, a `test.py` command script is mentioned, but this file is missing from the repository.

**Comment by albanie** [comment]
Thanks for pointing this out!  That was a typo in the README. I've updated it to explain that to evaluate the features, you re-run the training script to train the keypoint regressor.  We could probably also release the small regressor weights themselves, which produce the exact numbers reported in the README, it would just take a few modifications.  Let me know if you hit further issues.

**Comment by schuhschuh** [comment]
Yes, the learned weights of the keypoint regressor would be a nice to have. But this works for me as well as is. Thanks!
